version: "3.3"

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: deploy/docker/dev/nginx.Dockerfile
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=local.work.ru
      - NGINX_PORT=80
    links:
      - php
    volumes:
      - ./www:/var/www
      - ./volumes/nginx-logs:/var/log/nginx

  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: deploy/docker/dev/php.Dockerfile
    volumes:
      - ./www:/var/www
    links:
      - db

  db:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "local.work.ru"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./volumes/pgsql-db-volume:/var/lib/postgresql/data